# fly.toml app configuration file generated for polybot-course on 2026-09-12T23:51:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'polybot-course'
primary_region = 'iad'

[build]
[env]
  COURSE_HOST = '0.0.0.0'
  COURSE_PORT = '4000'

[processes]
  app = 'node dist/src/course-server.js'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
